mod "stdlib",
  :git => "git://github.com/puppetlabs/puppetlabs-stdlib.git"

mod "concat",
  :git => "git://github.com/puppetlabs/puppetlabs-concat.git"

mod "puppetlabs/apache",
  :git => 'git://github.com/puppetlabs/puppetlabs-apache.git'

mod "apt",
  :git => "git://github.com/puppetlabs/puppetlabs-apt.git"

mod "php",
  :git => "git://github.com/example42/puppet-php.git"

mod "xdebug",
  :git => "git://github.com/puphpet/puphpet-xdebug.git"

mod "puphpet",
  :git => "git://github.com/puphpet/puppet-puphpet.git"

mod "composer",
  :git => "git://github.com/puphpet/puphpet-composer.git"

mod "mysql",
  :git => "git://github.com/puppetlabs/puppetlabs-mysql.git"

mod "postgresql",
  :git => "git://github.com/puppetlabs/puppetlabs-postgresql.git"
